name = "Shenannigains"
author = "FrostyTacos"
version = "1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6a3aa23ff5a5116b054aa97d1ac50f259a3fa88018978fed87780f9978a290a8"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.228"
