name = "Shenannigains"
author = "FrostyTacos"
version = "1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8e385989f8243b1c000be2a53541da3483110999baaedc7084f3254d29969b8a"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.228"
